// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockWisdomRepository is an autogenerated mock type for the WisdomRepository type
type MockWisdomRepository struct {
	mock.Mock
}

type MockWisdomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWisdomRepository) EXPECT() *MockWisdomRepository_Expecter {
	return &MockWisdomRepository_Expecter{mock: &_m.Mock}
}

// ExtractWisdom provides a mock function with given fields:
func (_m *MockWisdomRepository) ExtractWisdom() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExtractWisdom")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWisdomRepository_ExtractWisdom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractWisdom'
type MockWisdomRepository_ExtractWisdom_Call struct {
	*mock.Call
}

// ExtractWisdom is a helper method to define mock.On call
func (_e *MockWisdomRepository_Expecter) ExtractWisdom() *MockWisdomRepository_ExtractWisdom_Call {
	return &MockWisdomRepository_ExtractWisdom_Call{Call: _e.mock.On("ExtractWisdom")}
}

func (_c *MockWisdomRepository_ExtractWisdom_Call) Run(run func()) *MockWisdomRepository_ExtractWisdom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWisdomRepository_ExtractWisdom_Call) Return(_a0 string, _a1 error) *MockWisdomRepository_ExtractWisdom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWisdomRepository_ExtractWisdom_Call) RunAndReturn(run func() (string, error)) *MockWisdomRepository_ExtractWisdom_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWisdomRepository creates a new instance of MockWisdomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWisdomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWisdomRepository {
	mock := &MockWisdomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
