// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockWisdomBearer is an autogenerated mock type for the WisdomBearer type
type MockWisdomBearer struct {
	mock.Mock
}

type MockWisdomBearer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWisdomBearer) EXPECT() *MockWisdomBearer_Expecter {
	return &MockWisdomBearer_Expecter{mock: &_m.Mock}
}

// ExpandWisdom provides a mock function with given fields: ctx
func (_m *MockWisdomBearer) ExpandWisdom(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExpandWisdom")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWisdomBearer_ExpandWisdom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpandWisdom'
type MockWisdomBearer_ExpandWisdom_Call struct {
	*mock.Call
}

// ExpandWisdom is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockWisdomBearer_Expecter) ExpandWisdom(ctx interface{}) *MockWisdomBearer_ExpandWisdom_Call {
	return &MockWisdomBearer_ExpandWisdom_Call{Call: _e.mock.On("ExpandWisdom", ctx)}
}

func (_c *MockWisdomBearer_ExpandWisdom_Call) Run(run func(ctx context.Context)) *MockWisdomBearer_ExpandWisdom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockWisdomBearer_ExpandWisdom_Call) Return(_a0 string, _a1 error) *MockWisdomBearer_ExpandWisdom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWisdomBearer_ExpandWisdom_Call) RunAndReturn(run func(context.Context) (string, error)) *MockWisdomBearer_ExpandWisdom_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWisdomBearer creates a new instance of MockWisdomBearer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWisdomBearer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWisdomBearer {
	mock := &MockWisdomBearer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
