openapi: 3.0.0
info:
  title: Word of Wisdom TCP Server
  version: 1.0.0
  description: A TCP api protected by Hashcash Proof of Work (PoW) that returns wisdom quotes after challenge verification.

servers:
  - url: http://localhost:8080
    description: Local development api

paths:
  /challenge:
    get:
      summary: Get PoW Hashcash challenge
      operationId: GetChallenge
      responses:
        '200':
          description: Challenge generated successfully
          headers:
            X-Remark:
              description: A unique identifier for the challenge
              schema:
                type: string
                format: uuid
          content:
            application/json:
              schema:
                type: object
                properties:
                  difficulty:
                    type: integer
                    description: Amount of leading zeroes in resulting hash
                  challenge:
                    type: string
                    description: The PoW challenge for the client to solve

  /verify:
    post:
      summary: Verify Hashcash PoW solution
      operationId: VerifySolution
      parameters:
        - in: header
          name: X-Remark
          description: A unique identifier for the challenge to verify
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                challenge:
                  type: string
                  description: The challenge string provided by the api
                nonce:
                  type: string
                  description: The solution (nonce) provided by the client
      responses:
        '200':
          description: PoW solution verified successfully, returns wisdom quote
          content:
            application/json:
              schema:
                type: object
                properties:
                  quote:
                    type: string
                    description: The wisdom quote returned after successful verification
        '400':
          description: Invalid PoW solution
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message